### ISSUE TITLE
Native filesystem globbing

### ISSUE THREAD

**Issue by jaychia** [Eventual-Inc/Daft#1421]
Implement globbing over filesystems using native Rust code.

**Acceptance Criteria**

1. Globbing works over all target backends (S3, GCS, Azure, HTTP, local)
2. Integration tests running in CI
3. Stress test (deeply nested S3 globbing) works without deadlocking issues

**Tasks**

`.ls` for each of the following backends:

- [x] Implement S3 `.ls`
- [x] Implement  GCS `.ls`
- [ ] Implement Azure `.ls`: #1439 
- [ ] Implement HTTP `.ls`: #1440 
- [ ] Implement local `.ls`: #1441 

Separately, we need to implement globbing logic which takes advantage of `.ls` in each backend to return all paths that match the provided glob path:

- [ ] Implement glob `.glob(globpath) { while keep_going(globpath, current) { ls(current) } ...}`

Lastly, we can then deprecate `fsspec`:

- [ ] #1438 

Known bugs:

We should verify that our new solution fixes some known issues with the old solution

- [ ] Handle colons in provided filepath (#687)
