### ISSUE TITLE
Native file I/O

### ISSUE THREAD

**Issue by jaychia** [Eventual-Inc/Daft#1422]
# Summary

Reading and writing data from storage is crucial to Daft's performance.

## Acceptance Criteria

1. `IOConfig` object is correctly utilized for all I/O operations -- i.e. user-provided credentials will be used for file listing, reading and writing across all file formats and backends.
2. Daft provides an efficient implementation of **reading** data for CSV, JSON and Parquet at PyArrow-level of performance or better
3. Daft provides an efficient implementation of **writing** data for CSV, JSON and Parquet at PyArrow-level of performance or better
4. Deprecate usage of fsspec everywhere in the Daft codebase

**Known bugs**

We should check these off when we can verify that new implementations take care of them

- [ ] Writing to location with existing file throws an ambiguous error message (see: #469)
- [ ] Filepaths with colons are not handled correctly during globbing (see: #687)
- [ ] Handle newlines when parsing CSV (see: #902)

## Progress tracking

- [ ] Native listing of files (see: #1421)
- [ ] Deprecate use of `fsspec` to pass credentials to Daft (this has a last remaining dependency on #1421 and on tasks listed below under "IOConfig credentials propagation")

IOConfig credentials propagation:

- [x] Using IOConfig for reads of Parquet
- [ ] Using IOConfig for reads of JSON
- [ ] Using IOConfig for reads of CSV
- [ ] Using IOConfig for writes of JSON
- [ ] Using IOConfig for writes of CSV
- [ ] Using IOConfig for writes of Parquet

Rust implementations per-file format:

- [x] Rust implementation for reads of Parquet
- [ ] Rust implementation for reads of CSV
- [ ] Rust implementation for reads of JSON
- [ ] Rust implementation for writes of Parquet
- [ ] Rust implementation for writes of CSV
- [ ] Rust implementation for writes of JSON

**Comment by jaychia** [comment]
I'd like to propose knocking out all the tasks under `IOConfig credentials propagation` and `Deprecate use of fsspec to pass credentials to Daft` this week!

We can then start working on `Rust implementations per-file format` (maybe as a separate ticket) by first measuring performance/understanding how much performance we're getting vs effort we need to spend on each file format.
