### ISSUE TITLE
Iceberg Support Roadmap

### ISSUE THREAD

**Issue by kevinzwang** [Eventual-Inc/Daft#2458]
## Features
- [x] Basic reads
- [x] Partitioned reads
- [x] Basic writes
- [x] Merge-on-read position delete reads
- [ ] Merge-on-read equality delete reads
  - blocked by pyiceberg
- [ ] Utilizing statistics from table format
- [ ] #1953
- [x] Field IDs
- [ ] https://github.com/Eventual-Inc/Daft/issues/2105
- [ ] https://github.com/Eventual-Inc/Daft/issues/2249
- [x] Partitioned writes (https://github.com/Eventual-Inc/Daft/pull/2842)
- [ ] Upserts/`MERGE` https://github.com/Eventual-Inc/Daft/issues/3844
  - [ ] Copy-on-write writing
  - [ ] Merge-on-read writing 
- [ ] Add support for writing new Iceberg tables to catalogs such as AWS Glue and Iceberg REST
- [ ] https://github.com/Eventual-Inc/Daft/issues/3823

## Bugs and Testing
- [ ] https://github.com/Eventual-Inc/Daft/issues/2129
- [ ] https://github.com/Eventual-Inc/Daft/issues/2459
- [ ] https://github.com/Eventual-Inc/Daft/issues/2348

**Comment by corleyma** [comment]
@kevinzwang I am a bit confused about what `copy-on-write writing` represents in this set of features?  Typically (at least coming from a Spark lens), copy-on-write as the default behavior for Iceberg v2 tables.  Given that Daft supports basic and partitioned rights, what does it mean to say Daft does not have support for either COW or MOR writing?  It has to be one or the other, right?

**Comment by kevinzwang** [comment]
> @kevinzwang I am a bit confused about what `copy-on-write writing` represents in this set of features? Typically (at least coming from a Spark lens), copy-on-write is the default behavior for Iceberg v2 tables. Given that Daft supports basic and partitioned rights, what does it mean to say Daft does not have support for either COW or MOR writing? It has to be one or the other, right?

Hi @corleyma! COW and MOR are two different strategies we would need to support in order to do upsert (MERGE/DELETE) operations in Iceberg. We currently only support append or overwrite for writing to Iceberg tables, which do not need either.

**Comment by asparsh607** [comment]
@kevinzwang @rchowell Any updates on merge operation?

**Comment by rchowell** [comment]
Hey @asparsh607 this work is not prioritized at the moment.
