### ISSUE TITLE
EPIC: spark connect

### ISSUE THREAD

**Issue by universalmind303** [Eventual-Inc/Daft#3581]
### Session
- [x] config.set
- [x] config.get
- [x] config.unset
- [x] config.getAll
- [x] createDataFrame
- [x] sql
- [ ] udf

### DataFrame

- [x] limit, 
- [x] range, 
- [x] project, 
- [ ] join
- [x] agg(groupby)
- [ ] agg
- [ ] agg(rollup)
- [ ] agg(cube)
- [ ] agg(pivot)
- [ ] agg(grouping sets)
- [x] drop
- [x] filter
- [x] sort
- set operations
  - [x] except
  - [x] intersect
  - [x] union
- [x] in memory/local rel
- [x] with_columns
- [x] rename_columns
- [x] .schema()
- [x] .collect()
- [x] .show()
- [x] .explain()
- [x] read.csv (header, delimiter, inferSchema, chunk_size)
- [x] read.parquet (hive_partitioning, chunk_size)
- [x] read.json
- [x] read.delta
- [x] write.csv (missing write options)
- [x] write.json (missing write options)
- [x] write.parquet (missing write options)
- [ ] write._ (partitionBy)
- [x] createOrReplaceTempView
- [x] toPandas
- [ ] mapPartitions

### Catalog

TODO (I don't think this is stabilized in spark connect yet)

### pyspark.sql.functions

see [https://spark.apache.org/docs/latest/api/python/reference/pyspark.sql/functions.html](https://spark.apache.org/docs/latest/api/python/reference/pyspark.sql/functions.html) for list of functions

Expressions:
- agg functions
  - [x] count
  - [x] mean
  - [x] stddev
  - [x] min
  - [x] max
  - [x] sum
- Operators
  - [x] "=="
  - [x] "!="
  - [x] "<"
  - [x] "<="
  - [x] ">"
  - [x] ">="
  - [x] "+"
  - [x] "-"
  - [x] "*"
  - [x] "/"
  - [x] "//"
  - [x] "%"
  - [x] "&"
  - [x] "|"
  - [x] "^"
  - [x] "<<"
  - [x] ">>"
- Normal functions
  - [x] coalesce
  - [x] isnan
  - [x] isnull
  - [ ] monotically_increasing_id
  - [ ] named_struct
  - [ ] nanvl
  - [ ] rand
  - [ ] randn
  - [ ] spark_partition_id
  - [ ] when
  - [ ] bitwise_not
  - [ ] bitwiseNOT
  - [ ] expr
  - [ ] greatest
  - [ ] least
  - [x] isnotnull
  - [x] isnull
  - [x] not
  
#### UDFS

spark UDF's *should* be mappable to our UDF's. They use a very similar pickling approach, and we'll likely just need to use their deserializer to deserialize them back into python. Likely a bit more discovery needed.

### UX/DX

- [ ] [https://github.com/Eventual-Inc/Daft/issues/3551](https://github.com/Eventual-Inc/Daft/issues/3551)
- [ ] [https://github.com/Eventual-Inc/Daft/issues/3497](https://github.com/Eventual-Inc/Daft/issues/3497)
- [ ] [https://github.com/Eventual-Inc/Daft/issues/3582](https://github.com/Eventual-Inc/Daft/issues/3582)

### Documentation

- [ ] Quick start guide for spark connect via daft (daft connect)
- [ ] Distributed computing guide for daft connect
  * this should include a guide for how to set up a cluster and connect to it via spark.

## Issue Tracking

- [ ] [https://github.com/Eventual-Inc/Daft/issues/3577](https://github.com/Eventual-Inc/Daft/issues/3577)
- [ ] [https://github.com/Eventual-Inc/Daft/issues/3551](https://github.com/Eventual-Inc/Daft/issues/3551)
- [ ] [https://github.com/Eventual-Inc/Daft/issues/3550](https://github.com/Eventual-Inc/Daft/issues/3550)
- [ ] [https://github.com/Eventual-Inc/Daft/issues/3498](https://github.com/Eventual-Inc/Daft/issues/3498)
- [ ] [https://github.com/Eventual-Inc/Daft/issues/3497](https://github.com/Eventual-Inc/Daft/issues/3497)
- [ ] [https://github.com/Eventual-Inc/Daft/issues/3486](https://github.com/Eventual-Inc/Daft/issues/3486)
- [ ] [https://github.com/Eventual-Inc/Daft/issues/3424](https://github.com/Eventual-Inc/Daft/issues/3424)
- [ ] [https://github.com/Eventual-Inc/Daft/issues/3609](https://github.com/Eventual-Inc/Daft/issues/3609)

## Upstream Spark issues

- [ ] [https://issues.apache.org/jira/browse/SPARK-50627](https://issues.apache.org/jira/browse/SPARK-50627)
- [ ] [https://issues.apache.org/jira/browse/SPARK-50626](https://issues.apache.org/jira/browse/SPARK-50626)

**Comment by jaychia** [comment]
WRT to the catalogs, @universalmind303 what do you think of starting to unify around the DaftMetaCatalog that I introduced in #3036?

I think we have a few competing standards atm (including the SQLCatalog). It could be good to start having a catalog abstraction that can be shared across our different frontends

**Comment by universalmind303** [comment]
> WRT to the catalogs, @universalmind303 what do you think of starting to unify around the DaftMetaCatalog that I introduced in #3036?
> 
> I think we have a few competing standards atm (including the SQLCatalog). It could be good to start having a catalog abstraction that can be shared across our different frontends

yes, that is something I want to do and have been thinking about. I'll open up an issue to unify `daft.catalog` and `daft.sql.catalog`

**Comment by universalmind303** [comment]
closing this issue as there's been little interest in spark connect.
